# This file was automatically generated by makemake.
# Do not edit it directly!
# Any changes you make will be silently overwritten.

# Edit this file to define constants and custom build targets.
# Please refer to the makemake documentation for more information.
#
# To compile multiple versions of a program or library, please study
#     http://www.its.caltech.edu/~jafl/jcc/multi_version.html

# Useful directories

INSTALL_DIR	:=	/usr/local

MYCODEDIR := ./src

# Directories to search for header files

SEARCHDIRS := -I- -I${MYCODEDIR} -I/usr/X11R6/include

# makemake variables

DEPENDFLAGS := -g -Wall  ${SEARCHDIRS}

# C preprocessor (C, C++, FORTRAN)

CPPFLAGS = 

# C compiler

CC     := gcc
CFLAGS  = ${DEPENDFLAGS}

%.o : %.c
	${CC} ${CPPFLAGS} ${CFLAGS} -c $< -o $@

# C++ compiler

CXX      := c++
CXXFLAGS  = ${DEPENDFLAGS}

%.o : %.cc
	${CXX} ${CPPFLAGS} ${CXXFLAGS} -c $< -o $@

%.o : %.C
	${CXX} ${CPPFLAGS} ${CXXFLAGS} -c $< -o $@

%.o : %.cpp
	${CXX} ${CPPFLAGS} ${CXXFLAGS} -c $< -o $@

%.o : %.cxx
	${CXX} ${CPPFLAGS} ${CXXFLAGS} -c $< -o $@

# FORTRAN compiler

FC     := f77
FFLAGS  = 

# C/C++/Eiffel/FORTRAN linker

LINKER    := gcc
LDFLAGS    = -L/usr/X11R6/lib
LOADLIBES := -lXpm -lXext -lX11 -lm 

# Java compiler

JAVAC  := javac
JFLAGS  = 
JAR    := jar

%.class : %.java
	${JAVAC} ${JFLAGS} $<

.PHONY	:	default	
defult::	all


# Installation
.PHONY	:	install
install:	
	@chmod a+x			hazewm
	@chmod a+x			starthaze
	@cp -f hazewm		$(INSTALL_DIR)/bin/
	@cp -f starthaze	$(INSTALL_DIR)/bin/
	@mkdir -p			$(INSTALL_DIR)/share/haze
	@cp -f pixmap/*		$(INSTALL_DIR)/share/haze


.PHONY	:	uninstall
uninstall:	
	@rm -f				$(INSTALL_DIR)/bin/hazewm
	@rm -f -R			$(INSTALL_DIR)/share/haze



# This is what makemake added


# hazewm

hazewm : ./src/add_window.o ./src/balloon.o ./src/borders.o ./src/config.o ./src/event.o ./src/functions.o ./src/main.o ./src/menus.o ./src/misc.o ./src/wild.o
	${LINKER} ${LDFLAGS} -o $@ ${filter-out %.a %.so, $^} ${LOADLIBES}

# target for making everything

.PHONY : all
all: hazewm


# target for removing all object files

.PHONY : tidy
tidy::
	@${RM} core ./src/add_window.o ./src/balloon.o ./src/borders.o ./src/config.o ./src/event.o ./src/functions.o ./src/main.o ./src/menus.o ./src/misc.o ./src/wild.o

# target for removing all object files

.PHONY : clean
clean:: tidy
	@${RM} hazewm

# list of all source files

MM_ALL_SOURCES := ./src/add_window.c ./src/balloon.c ./src/borders.c ./src/config.c ./src/event.c ./src/functions.c ./src/main.c ./src/menus.c ./src/misc.c ./src/wild.c


# target for checking a source file

CHECKSYNTAXFILE := ${basename ${filter %${CHECKSTRING}, ${MM_ALL_SOURCES}}}

.PHONY : checksyntax
checksyntax:
  ifneq (${CHECKSYNTAXFILE},)
	@${MAKE} ${addsuffix .o, ${CHECKSYNTAXFILE}}
  else
	@echo No target to make ${CHECKSTRING}
  endif


# target for touching appropriate source files

.PHONY : touch
touch::
	@list=$$(grep -l ${TOUCHSTRING} ${MM_ALL_SOURCES}); \
     for file in $$list; do { echo $$file; touch $$file; } done


# target for calculating dependencies (MAKEMAKE)

.PHONY : jdepend
jdepend:
	@${MAKEMAKE} --depend Makefile -- ${DEPENDFLAGS} --  ./src/add_window.c ./src/add_window.o ./src/balloon.c ./src/balloon.o ./src/borders.c ./src/borders.o ./src/config.c ./src/config.o ./src/event.c ./src/event.o ./src/functions.c ./src/functions.o ./src/main.c ./src/main.o ./src/menus.c ./src/menus.o ./src/misc.c ./src/misc.o ./src/wild.c ./src/wild.o


# DO NOT DELETE THIS LINE -- makemake depends on it.

./src/add_window.o: ./src/borders.h ./src/config.h ./src/main.h ./src/menus.h ./src/misc.h ./src/screen.h ./src/sun_headers.h /usr/X11R6/include/X11/X.h /usr/X11R6/include/X11/Xatom.h /usr/X11R6/include/X11/Xfuncproto.h /usr/X11R6/include/X11/Xlib.h /usr/X11R6/include/X11/Xmd.h /usr/X11R6/include/X11/Xosdefs.h /usr/X11R6/include/X11/Xresource.h /usr/X11R6/include/X11/Xutil.h /usr/X11R6/include/X11/cursorfont.h /usr/X11R6/include/X11/extensions/shape.h /usr/X11R6/include/X11/xpm.h /usr/include/malloc.h /usr/include/stdio.h /usr/include/stdlib.h /usr/include/sys/resource.h /usr/include/sys/time.h /usr/include/sys/types.h /usr/include/sys/wait.h /usr/include/unistd.h

./src/balloon.o: ./src/config.h ./src/event.h ./src/main.h ./src/menus.h ./src/misc.h ./src/screen.h ./src/sun_headers.h /usr/X11R6/include/X11/X.h /usr/X11R6/include/X11/Xfuncproto.h /usr/X11R6/include/X11/Xlib.h /usr/X11R6/include/X11/Xmd.h /usr/X11R6/include/X11/Xosdefs.h /usr/X11R6/include/X11/Xutil.h /usr/X11R6/include/X11/cursorfont.h /usr/X11R6/include/X11/extensions/shape.h /usr/X11R6/include/X11/xpm.h /usr/include/malloc.h /usr/include/stdio.h /usr/include/stdlib.h /usr/include/sys/resource.h /usr/include/sys/time.h /usr/include/sys/types.h /usr/include/sys/wait.h /usr/include/unistd.h

./src/borders.o: ./src/borders.h ./src/config.h ./src/main.h ./src/menus.h ./src/misc.h ./src/screen.h ./src/sun_headers.h /usr/X11R6/include/X11/X.h /usr/X11R6/include/X11/Xfuncproto.h /usr/X11R6/include/X11/Xlib.h /usr/X11R6/include/X11/Xmd.h /usr/X11R6/include/X11/Xosdefs.h /usr/X11R6/include/X11/Xutil.h /usr/X11R6/include/X11/cursorfont.h /usr/X11R6/include/X11/extensions/shape.h /usr/X11R6/include/X11/xpm.h /usr/include/malloc.h /usr/include/stdio.h /usr/include/stdlib.h /usr/include/string.h /usr/include/sys/resource.h /usr/include/sys/time.h /usr/include/sys/types.h /usr/include/sys/wait.h /usr/include/unistd.h

./src/config.o: ./src/config.h ./src/main.h ./src/menus.h ./src/misc.h ./src/screen.h ./src/sun_headers.h /usr/X11R6/include/X11/X.h /usr/X11R6/include/X11/Xfuncproto.h /usr/X11R6/include/X11/Xlib.h /usr/X11R6/include/X11/Xmd.h /usr/X11R6/include/X11/Xosdefs.h /usr/X11R6/include/X11/Xutil.h /usr/X11R6/include/X11/cursorfont.h /usr/X11R6/include/X11/xpm.h /usr/include/ctype.h /usr/include/malloc.h /usr/include/stdio.h /usr/include/stdlib.h /usr/include/string.h /usr/include/sys/resource.h /usr/include/sys/time.h /usr/include/sys/types.h /usr/include/sys/wait.h /usr/include/unistd.h

./src/event.o: ./src/add_window.h ./src/balloon.h ./src/borders.h ./src/config.h ./src/functions.h ./src/main.h ./src/menus.h ./src/misc.h ./src/screen.h ./src/sun_headers.h /usr/X11R6/include/X11/X.h /usr/X11R6/include/X11/Xatom.h /usr/X11R6/include/X11/Xfuncproto.h /usr/X11R6/include/X11/Xlib.h /usr/X11R6/include/X11/Xmd.h /usr/X11R6/include/X11/Xosdefs.h /usr/X11R6/include/X11/Xutil.h /usr/X11R6/include/X11/cursorfont.h /usr/X11R6/include/X11/extensions/shape.h /usr/X11R6/include/X11/xpm.h /usr/include/malloc.h /usr/include/stdio.h /usr/include/stdlib.h /usr/include/string.h /usr/include/sys/resource.h /usr/include/sys/time.h /usr/include/sys/types.h /usr/include/sys/wait.h /usr/include/unistd.h

./src/functions.o: ./src/balloon.h ./src/borders.h ./src/config.h ./src/event.h ./src/functions.h ./src/main.h ./src/menus.h ./src/misc.h ./src/screen.h ./src/sun_headers.h /usr/X11R6/include/X11/X.h /usr/X11R6/include/X11/Xfuncproto.h /usr/X11R6/include/X11/Xlib.h /usr/X11R6/include/X11/Xmd.h /usr/X11R6/include/X11/Xosdefs.h /usr/X11R6/include/X11/Xutil.h /usr/X11R6/include/X11/cursorfont.h /usr/X11R6/include/X11/xpm.h /usr/include/malloc.h /usr/include/stdio.h /usr/include/stdlib.h /usr/include/string.h /usr/include/sys/resource.h /usr/include/sys/time.h /usr/include/sys/types.h /usr/include/sys/wait.h /usr/include/unistd.h

./src/main.o: ./src/add_window.h ./src/config.h ./src/event.h ./src/functions.h ./src/main.h ./src/menus.h ./src/misc.h ./src/screen.h ./src/sun_headers.h /usr/X11R6/include/X11/X.h /usr/X11R6/include/X11/Xatom.h /usr/X11R6/include/X11/Xfuncproto.h /usr/X11R6/include/X11/Xlib.h /usr/X11R6/include/X11/Xlocale.h /usr/X11R6/include/X11/Xmd.h /usr/X11R6/include/X11/Xosdefs.h /usr/X11R6/include/X11/Xproto.h /usr/X11R6/include/X11/Xprotostr.h /usr/X11R6/include/X11/Xresource.h /usr/X11R6/include/X11/Xutil.h /usr/X11R6/include/X11/cursorfont.h /usr/X11R6/include/X11/extensions/shape.h /usr/X11R6/include/X11/xpm.h /usr/include/fcntl.h /usr/include/locale.h /usr/include/malloc.h /usr/include/signal.h /usr/include/stdio.h /usr/include/stdlib.h /usr/include/string.h /usr/include/sys/resource.h /usr/include/sys/time.h /usr/include/sys/types.h /usr/include/sys/wait.h /usr/include/unistd.h

./src/menus.o: ./src/add_window.h ./src/borders.h ./src/config.h ./src/event.h ./src/functions.h ./src/main.h ./src/menus.h ./src/misc.h ./src/screen.h ./src/sun_headers.h /usr/X11R6/include/X11/X.h /usr/X11R6/include/X11/Xatom.h /usr/X11R6/include/X11/Xfuncproto.h /usr/X11R6/include/X11/Xlib.h /usr/X11R6/include/X11/Xmd.h /usr/X11R6/include/X11/Xosdefs.h /usr/X11R6/include/X11/Xresource.h /usr/X11R6/include/X11/Xutil.h /usr/X11R6/include/X11/cursorfont.h /usr/X11R6/include/X11/extensions/shape.h /usr/X11R6/include/X11/xpm.h /usr/include/ctype.h /usr/include/malloc.h /usr/include/stdio.h /usr/include/stdlib.h /usr/include/string.h /usr/include/sys/resource.h /usr/include/sys/time.h /usr/include/sys/types.h /usr/include/sys/wait.h /usr/include/unistd.h

./src/misc.o: ./src/config.h ./src/main.h ./src/menus.h ./src/screen.h ./src/sun_headers.h /usr/X11R6/include/X11/X.h /usr/X11R6/include/X11/Xfuncproto.h /usr/X11R6/include/X11/Xlib.h /usr/X11R6/include/X11/Xmd.h /usr/X11R6/include/X11/Xosdefs.h /usr/X11R6/include/X11/Xutil.h /usr/X11R6/include/X11/cursorfont.h /usr/X11R6/include/X11/xpm.h /usr/include/ctype.h /usr/include/malloc.h /usr/include/stdio.h /usr/include/stdlib.h /usr/include/string.h /usr/include/sys/resource.h /usr/include/sys/time.h /usr/include/sys/types.h /usr/include/sys/wait.h /usr/include/unistd.h

./src/wild.o: /usr/include/stdio.h

